### ISSUE TITLE
Enable Jest code coverage

### ISSUE THREAD

**Issue by SebastianM** [SebastianM/tinystate#3]
When I run `yarn test -- --watch --collectCoverage`, I get the following error:

```
 FAIL  src/plugins/redux_devtools.spec.ts
  ● Test suite failed to run

    TypeError: /Users/sebmueller/projects/tinystate/src/plugins/redux_devtools.ts: Cannot read property 'some' of undefined

      at VisitState.onEnter (node_modules/istanbul-lib-instrument/dist/visitor.js:141:71)
      at VisitState.wrappedEntry (node_modules/istanbul-lib-instrument/dist/visitor.js:336:14)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:190:19)
      at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:115:19)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.515s
Ran all test suites related to changed files.
```

**Comment by SebastianM** [comment]
Found the issue...got fixed 22 hours ago: https://github.com/istanbuljs/istanbuljs/commit/5dd88e8df6a225cf40fe044689ca44a3050746a3
